name: "Copilot Setup Steps"

# Allows you to test the setup steps from your repository's "Actions" tab
on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    # Set the permissions to the lowest permissions possible needed for *your steps*. Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission.
      # If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read
    steps:
        - name: Checkout code
          uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

        - name: Set up Node.js
          uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
          with:
            node-version: '22'

        - name: Install JavaScript dependencies
          run: npm ci
